services:
    proxy-nginx-proxy:
        container_name: ${STACK_NAME}-nginx-proxy
        image: nginxproxy/nginx-proxy:${NGINX_PROXY_VERSION}
        restart: unless-stopped
        environment:
            ENABLE_IPV6: 'true'
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../conf:/etc/nginx/conf.d
            - ../vhost:/etc/nginx/vhost.d
            - ../html:/usr/share/nginx/html
            - ../dhparam:/etc/nginx/dhparam
            - ../certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro

    proxy-acme-companion:
        container_name: ${STACK_NAME}-acme-companion
        image: nginxproxy/acme-companion:${ACME_COMPANION_VERSION}
        restart: unless-stopped
        depends_on:
            - proxy-nginx-proxy
        volumes:
            - ../vhost:/etc/nginx/vhost.d
            - ../html:/usr/share/nginx/html
            - ../dhparam:/etc/nginx/dhparam
            - ../certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            NGINX_PROXY_CONTAINER: proxy-nginx-proxy
            FILES_UID: ${USER_ID}
            FILES_GID: ${GROUP_ID}
            FILES_PERMS: 644
        profiles:
            - acme

    proxy-self-signed-companion:
        container_name: ${STACK_NAME}-self-signed-companion
        image: sebastienheyd/self-signed-proxy-companion:${SELF_SIGNED_VERSION}
        restart: unless-stopped
        depends_on:
            - proxy-nginx-proxy
        volumes:
            - ../certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            NGINX_PROXY_CONTAINER: proxy-nginx-proxy
        profiles:
            - self-signed

networks:
    default:
        external: true
        name: ${NETWORK_NAME}
